// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const ErrorBoundary: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/ErrorBoundary').ErrorBoundary
  const Footer: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/Footer').default
  const GradeBadge: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/GradeBadge').default
  const Header: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/Header').default
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const Layout: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/Layout').default
  const LearningRoadmap: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/LearningRoadmap').default
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const Sidebar: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/Sidebar').default
  const TechLogo: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/TechLogo').default
  const analyzePerformance: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/utils/analysis').analyzePerformance
  const analyzeSecurity: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/utils/analysis').analyzeSecurity
  const browser: typeof import('wxt/browser').browser
  const buildLayers: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/utils/analysis').buildLayers
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getBrandColor: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/utils/logos').getBrandColor
  const getCategoryBreakdown: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/utils/analysis').getCategoryBreakdown
  const getLogoFallback: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/utils/logos').getLogoFallback
  const getSlug: typeof import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/utils/logos').getSlug
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { ErrorBoundary } from 'C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/ErrorBoundary'
  import('C:/Users/pawan/SNPSU/Projects/Completed Projects/JIT - Browser Extension Studio/Stacklens/src/components/ErrorBoundary')
}
